name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#
env:
  FROM_YEAR: 1400
  TO_YEAR: 1401

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run main file
      run: |
        python ./src/main.py --From $FROM_YEAR --To $TO_YEAR

    - name:  Archive output artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-artifact
        path: ./output/*.json
        retention-days: 10